### ISSUE TITLE
JSON in data-* attributes

### ISSUE THREAD

**Issue by nlemoine** [voku/HtmlMin#35] opened 2019-06-03 14:16 UTC
#### What is this feature about (expected vs actual behaviour)?

Minification is breaking JSON placed in data-* attributes. Actually, it doesn't "break" the JSON part, it replaces single quotes with double quotes. 

```html
<div data-json='{"key":"value"}'></div>
```
Becomes: 
```html
<div data-json="{"key":"value"}"></div>
```

Unfortunalety, you can't use single quotes in JSON. But you can use single quotes in HTML.

#### How can I reproduce it?

```php
<?php

require_once 'vendor/autoload.php';

use voku\helper\HtmlMin;

$htmlMin = new HtmlMin();

ob_start();
?>
<html>
  <body>
    <div data-json='{"key":"value"}'></div>
  </body>
</html>
<?php
$html = ob_get_clean();

echo $htmlMin->minify($html); 

```

#### Does it take minutes, hours or days to fix?

I have no idea, I didn't dig into code.

**Comment by voku** [comment] 2019-06-08 00:28
Thanks for the good bug report. :+1: The issue is fixed in version 3.1.7.

**Closed by voku** 2019-06-08 00:28 UTC
