### ISSUE TITLE
v3 unexpected whitespace removal

### ISSUE THREAD

**Issue by Bilge** [voku/HtmlMin#16] opened 2017-12-29 12:35 UTC
Before compression:
```html

                        <span>foo</span>
                                                    <a href="bar">baz</a>
                                    <span>bat</span>
```

After compression:

```html
<span>foo</span><a href=bar>baz</a><span>bat</span>
```

Notice that all whitespace has been removed, even though there was whitespace between `<span>` and `<a>` elements in the source. This is invalid because it changes the way content is displayed after compression.

**Comment by voku** [comment] 2017-12-29 22:17
I think the problem is already fixed with version 3.0.0 (take a look at the tests -> https://travis-ci.org/voku/HtmlMin/builds/323025901), but you need to update "voku/simple_html_dom" >= 4.1.3. With version 3.0.1 we will now force this vendor update.

**Comment by Bilge** [comment] 2017-12-29 22:30
It seems I was using 4.1.3.

```
  - Removing voku/portable-utf8 (4.0.1)
  - Updating voku/simple_html_dom (4.0.1 => 4.1.3): Downloading (100%)
  - Updating voku/html-min (2.0.4 => 3.0.0): Downloading (100%)
```

**Comment by Bilge** [comment] 2018-01-28 00:33
Whitespace before anchors are definitely being removed.

### Before

```html
<span>foo</span>                                         <span>bar</span>                                                                                                                         <a>baz</a>                                                                                 <a>bat</a>
```

### After

```html
<span>foo</span> <span>bar</span><a>baz</a><a>bat</a>
```

Note that the `foo` span is needed for the space to be deleted before the `baz` tag. Maybe the presence of this extra tag is breaking some special-casing code. Since there is whitespace before each of the `<a>` tags in the source there should still be a single whitespace before each of the output tags.

**Closed** 2018-12-18 00:06 UTC

**Comment by Bilge** [comment] 2018-12-18 00:08
Why closed?

**Comment by voku** [comment] 2018-12-18 00:15
I added tests (28 Jan) that passed on travis-ci and on my local laptop, so I can't fix a test that did not fail :/

**Comment by Bilge** [comment] 2018-12-18 08:07
I assure you there remain outstanding issues.

**Comment by jordanade** [comment] 2022-07-07 00:04
I'm still experiencing this issue!
